Fix equals sign not being accepted in `value` tag.
edwardez/bbob_dart pull request #7
Opened 2024-09-26 11:57 UTC by MartenM

This PR fixes the issue mentioned in #6.
It rewrites some of the parsing and adds additional tests.

**Tests:**
```bash
00:00 +42: All tests passed!
```

2024-11-08 08:10 UTC, edwardez requested changes

2024-11-08 08:10 UTC, edwardez commented on lib/src/bbob_parser/lexer.dart
> +           // Defo a name
AVOID abbreviations and acronyms unless they are obvious

https://dart.dev/effective-dart/documentation#avoid-abbreviations-and-acronyms-unless-they-are-obvious

```suggestion
           // Definitely a name
```

2024-11-08 08:10 UTC, edwardez commented on lib/src/bbob_parser/lexer.dart
> +    // Represents: https://github.com/JiLiZART/BBob/blob/99c629e66678e40cec7b924eda2f1bfe0d46b941/packages/bbob-parser/src/lexer.ts#L104
DO use /// doc comments to document members and types
https://dart.dev/effective-dart/documentation#do-use-doc-comments-to-document-members-and-types

```suggestion
    /// Returns next `TagState` by keeping grabbing chracters
    ///
    /// Represents: https://github.com/JiLiZART/BBob/blob/99c629e66678e40cec7b924eda2f1bfe0d46b941/packages/bbob-parser/src/lexer.ts#L104
```

2024-11-12 09:37 UTC, MartenM commented on lib/src/bbob_parser/lexer.dart
> +    // Represents: https://github.com/JiLiZART/BBob/blob/99c629e66678e40cec7b924eda2f1bfe0d46b941/packages/bbob-parser/src/lexer.ts#L104
```suggestion
    /// Processes part of a tag and returns a state that should be used for the next iteration.
    ///
    /// Represents: https://github.com/JiLiZART/BBob/blob/99c629e66678e40cec7b924eda2f1bfe0d46b941/packages/bbob-parser/src/lexer.ts#L104
```

2024-11-12 09:38 UTC, MartenM commented
Improved the documentation!

2024-11-12 23:12 UTC, edwardez reviewed
Thanks! LGTM, just a small comment before I can merge

2024-11-12 23:12 UTC, edwardez commented on lib/src/bbob_parser/lexer.dart
> -      return !isEqual && !isWhiteSpace;
looks like `isEqual` check is removed, is this intended?

2024-11-13 13:27 UTC, MartenM commented on lib/src/bbob_parser/lexer.dart
> -      return !isEqual && !isWhiteSpace;
Yes otherwise it will stop processing when an equals sign is read in a tag. For example `url=https://x/y=z`.

It's been a while though, but if you add it back I am pretty sure it would break tests :P

2024-11-14 06:18 UTC, edwardez commented on lib/src/bbob_parser/lexer.dart
> -      return !isEqual && !isWhiteSpace;
thank you!

2024-11-14 06:18 UTC, merged

2024-11-14 06:40 UTC, edwardez commented
published https://pub.dev/packages/bbob_dart/versions/0.2.2-dev.1/changelog